# Generated by Django 3.1.1 on 2020-09-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('price', models.IntegerField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=20)),
                ('money', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=None, max_length=30)),
                ('seller', models.CharField(default=1, max_length=30)),
                ('buyer', models.CharField(max_length=30, null=True)),
                ('date_sell_start', models.DateTimeField(auto_now_add=True)),
                ('date_buy', models.DateTimeField(null=True)),
                ('animal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.user')),
                ('parent1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='species_parent1', to='api.species')),
                ('parent2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='species_parent2', to='api.species')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to='api.user'),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to='api.user'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(default=None, max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='api.species'),
        ),
    ]
