# Generated by Django 3.1.1 on 2020-09-29 12:50

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(default=None),
        ),
    ]
